### ISSUE TITLE
Validating one object with different schemas overwrites previous validation messages.

### ISSUE THREAD

**Issue by ThijsJung** [williamwilling/okay#2]
# Context
I am using Okay to validate deeply nested Python objects of furniture data. Part of this data is shared by all types of furniture (dimensions, prices, colors, etc) but some attributes are specific to the type of furniture; e.g. a chair can have an armrest height while a lamp will not, and a lamp can have a cable length while a sofa will most probably not. To keep the schemas DRY I declared a `product_schema` for attributes shared by all types of furniture and a `chair_schema` with attributes specific to chairs. 

## Observed issue
After validating one chair with both schemas I want to collect all validation messages. I noticed that the validation messages of the `product_schema` are overwritten by the validation messages of the `chair_schema`. Below a sample program that illustrates the behaviour.

```
from okay import validate
from okay.schema import *

def product_schema():
    required('name', type='string')

def chair_schema():
    required('armrest_height_cm', type='int')
    optional('base_materials', type='list', min=1)

lounge_chair = {
    'name': 'Eames Lounge Chair',
    'armrest_height_cm': 56,
    'base_materials': ['aluminium'],
    'price_USD': 9783
}

product_validation_messages = validate(product_schema, lounge_chair)
print("Validation messages for the product schema:")
for message in product_validation_messages:
    print(f'{message.type}:\t{message.field}')
print()

print("Validation messages for the product schema, after validating the chair schema:")
_ = validate(chair_schema, lounge_chair)
for message in product_validation_messages:
    print(f'{message.type}:\t{message.field}')
```

Output:
```
Validation messages for the product schema:
extra_field:    armrest_height_cm
extra_field:    base_materials
extra_field:    price_USD

Validation messages for the product schema, after validating the chair schema:
extra_field:    name
extra_field:    price_USD
```

# Next up
My guess would be that this happens because the validation messages are returned by reference and `_validator._reset()` [clears the list in place instead of replacing it by a new one](https://github.com/williamwilling/okay/blob/1b646e3e370485fcc5a54293253b8599233052e8/src/okay/validator.py#L38). 

I expected the two lists of validation messages to be independent. Would that makes sense to you, too? If so, I'd be happy to create a P.R. to fix this. Let me know if that's something you welcome. Cheers!

**Comment by williamwilling** [comment]
Yeah, that's a bug.

Sounds like you want to have a go at fixing this, so please, be my guest. If you run into trouble, or you want me to take a stab at it, just let me know.

**Comment by ThijsJung** [comment]
Yes, I'd like to try and get my first contribution to an open source project under my belt! I'll read through the contribution docs and get started right away. I'll document any progress in this issue.

**Comment by ThijsJung** [comment]
I had some critical bugs at work that had to be fixed first, apologies for the tardy response. I have a branch ready to be attached to a P.R. but I'm not allowed to push my branch to the remote. I get the following error:

```bash
]$ git push -u origin fix/overwritten-validation-messages 
remote: Permission to williamwilling/okay.git denied to ThijsJung.
fatal: unable to access 'https://github.com/williamwilling/okay.git/': The requested URL returned error: 403
```

Could you give me access to push? Or am I doing something wrong?

**Comment by joost-basic-bits** [comment]
If I'm not mistaken, you should [fork the project](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks) and [create a pull request from the fork](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by williamwilling** [comment]
If I'm not mistaken, you should [fork the project](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks) and [create a pull request from the fork](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by ThijsJung** [comment]
Correct, that worked. I made a pull request, let me know what you think!

**Comment by ThijsJung** [comment]
Thanks for accepting the pull request! I don't see a new version yet, is that correct? Should we create one? And if so, would you like me to do it or do you want to do it yourself?

**Comment by williamwilling** [comment]
[Done.](https://github.com/williamwilling/okay/releases/tag/v2.0.1)

**Comment by ThijsJung** [comment]
You, good sir, are a lifesaver. Thank you!
